Change readability of header rows in PDF; tweak slack_report to not actually send report if --nosend specified, etc
royrapoport/channelstats pull request #16
Opened 2019-10-08 00:52 UTC by royrapoport

2019-10-08 16:31 UTC, jdq22 requested changes

2019-10-08 16:31 UTC, jdq22 commented on templates/general.html
> +                background:-o-linear-gradient(bottom, #ddd52a 5%, #ffffff 100%);	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ddd52a), color-stop(1, #ffffff) );	backg
Will you please drop in a screenshot so we can easily see how the readability was changed? (I'm assuming the change was in the more readable direction ;))

2019-10-08 16:31 UTC, jdq22 commented on slack_report.py
> +    raise RuntimeError("Must specify --destination if did not specify --nosend")
What are the expected inputs for `--destination`?

2019-10-09 02:35 UTC, royrapoport commented on templates/general.html
> +                background:-o-linear-gradient(bottom, #ddd52a 5%, #ffffff 100%);	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ddd52a), color-stop(1, #ffffff) );	backg
![image](https://user-images.githubusercontent.com/1121399/66447275-c7892980-ea02-11e9-8f30-535648b93ab7.png)

2019-10-09 02:40 UTC, royrapoport commented on templates/general.html
> +                background:-o-linear-gradient(bottom, #ddd52a 5%, #ffffff 100%);	background:-webkit-gradient( linear, left top, left bottom, color-stop(0.05, #ddd52a), color-stop(1, #ffffff) );	backg
![image](https://user-images.githubusercontent.com/1121399/66447519-6ca40200-ea03-11e9-934c-c88ee3ffca7a.png)

2019-10-09 02:40 UTC, royrapoport commented on slack_report.py
> +    raise RuntimeError("Must specify --destination if did not specify --nosend")
Either @username or #channel-name

2019-10-09 04:07 UTC, jdq22 approved these changes

2019-10-09 04:07 UTC, merged